linkLevelMin: 1
linkLevelMax: 3
memSavingMethod: 1

short: sentences, clauses, phrases in ETCBC transcription

description: >-
  <p>Syntactic structure search interface for <a id="corpus2link" href="#"></a>.</p>
  <p>This search interface is by:</p>
  <ul>
      <li><a id="author2link" href="#"></a> («author2.role»)
      <li><a id="author1link" href="#"></a> («author1.role»)
  </ul>

defaultSettings:
  autoexec: true
  nodeseq: true
  exporthl: true
  exportsr: true
  multihl: true
  simple: false

defaultFlags:
  i: false
  m: true
  s: false

keyboard:
  '┣': start of sentence
  '┫': end of sentence
  '├': start of sentence atom
  '┤': end of sentence atom
  '┏': start of clause
  '┓': end of clause
  '┌': start of clause atom
  '┐': end of clause atom
  '◀': start of phrase
  '▶': end of phrase
  '◁': start of phrase atom
  '▷': end of phrase atom

layerSettings:
  word:
    description: words (some words do not have a space between them)
    layers:
      lex:
        afterFeature: trailer
        default: ¿
        description: etcbc transcription of the lexemes
        feature: lex
        pos: null
        visible: true
      phono:
        afterFeature: phono_trailer
        default: ¿
        description: phonetic transliteration of full form
        feature: phono
        pos: null
        visible: true
      gloss:
        afterDefault: " "
        default: ¿
        description: word by word gloss
        ascend: lex
        feature: gloss
        pos: null
        visible: false
      pdp:
        afterDefault: " "
        default: z
        description: phrase-dependent part of speech
        feature: pdp
        pos: null
        visible: true
      png:
        afterDefault: " "
        default: z
        description: 'person(123) number(sdp)  gender(mf) state(ace)'
        feature: png
        pos: pdp
        visible: true
      vs:
        afterDefault: " "
        default: z
        description: verbal stem
        feature: vs
        pos: pdp
        visible: true
      vt:
        afterDefault: " "
        default: z
        description: verbal tense
        feature: vt
        pos: pdp
        visible: true
  phrase:
    nType: phrase_atom
    description: phrase atoms
    layers:
      ptype:
        default: -1
        description: phrase type
        ascend: phrase
        feature: typ
        pos: null
        visible: false
      function:
        default: -1
        description: phrase function
        ascend: phrase
        feature: function
        pos: ptype
        visible: true
  clause:
    nType: clause_atom
    description: clause atoms
    layers:
      ttype:
        default: -1
        description: text type
        ascend: clause
        feature: txt
        pos: null
        visible: false
      ctype:
        default: -1
        description: clause type
        ascend: clause
        feature: typ
        pos: null
        visible: false
      rela:
        default: -1
        description: clause relation
        ascend: clause
        feature: rela
        pos: ctype
        visible: true
  sentence:
    nType: sentence_atom
    focus: true
    description: sentence atoms
    layers:
      number:
        default: -1
        description: sentence atom number within the book
        feature: number
        pos: null
        visible: false
  verse:
    afterDefault: " "
    description: Verses may split sentences.
    layers:
      number:
        default: -1
        description: verse number
        feature: verse
        pos: null
        visible: true
  chapter:
    afterDefault: "\n"
    description: Chapters.
    layers:
      number:
        default: -1
        description: chapter number
        feature: chapter
        pos: null
        visible: true
  book:
    afterDefault: "\n"
    description: Books.
    layers:
      book:
        default: ¿
        description: name of a book
        feature: book@en
        pos: null
        visible: true
      ref:
        default: ¿
        description: latin name of a book
        feature: book
        pos: null
        visible: false
