const configData = {
 "mainConfig": {
  "description": {
   "simple": "<div id=\"title\">bhsa-structure search</div>",
   "full": "<details id=\"titledetails\">\n  <summary id=\"title\">bhsa-structure search</summary>\n  <div id=\"description\"></div>\n  <a\n     id=\"makerlink\" href=\"#\"\n     class=\"logo right\"\n  ><img alt=\"maker logo\" id=\"logo\" src=\"png/maker.png\"></a>\n  <a\n     id=\"tflink\" href=\"#\"\n     class=\"logo right\"\n  ><img alt=\"Text-Fabric logo\" id=\"logo\" src=\"png/tf.png\"></a>\n  <details>\n    <summary><i>open source</i></summary>\n    <div>\n      <p>You can\n      <a id=\"packagelink\" href=\"#\"></a>\n      this web page and use it offline\n      by unzipping and double clicking <i>structure-local.html</i>.\n      </p>\n      <p>This app is generated by <a id=\"generatorlink\" href=\"#\"></a>\n      based on a configuration in <a id=\"sourcelink\" href=\"#\"></a>.\n      </p>\n      <p>Written by: <a id=\"authorlink\" href=\"#\" ></a>.\n      <p>License: <a id=\"licenselink\" href=\"#\" ></a>\n      (you are free to use and modify the code).\n      </p>\n    </div>\n  </details>\n</details>"
  },
  "jobs": {
   "simple": "",
   "full": "<div id=\"jobs\">\n  <input\n    type=\"file\" name=\"imjname\" id=\"imjname\"\n    accept=\"application/json\"\n    class=\"import\"\n  >\n  <button\n    type=\"button\" class=\"medium active\" id=\"importj\"\n    title=\"import job from file\"\n  >↑</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"deletej\"\n    title=\"delete current job\"\n  >-</button>\n  <select class=\"selinp\" id=\"jchange\"></select>\n  <button\n    type=\"button\" class=\"medium active\" id=\"newj\"\n    title=\"fresh new job\"\n  >+</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"renamej\"\n    title=\"rename current job\"\n  >→</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"dupj\"\n    title=\"duplicate current job\"\n  >++</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"exportj\"\n    title=\"export job to file\"\n  >↓</button>\n</div>"
  },
  "provenance": {
   "simple": "<table>\n  <tbody>\n    <tr>\n      <td>help</td>\n      <td><a id=\"lsdocsimplelink\" href=\"#\"></a></td>\n    </tr>\n    <tr>\n      <td>data version</td>\n      <td><a id=\"datalink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>app version</td>\n      <td><span id=\"appversion\"></span></td>\n    </tr>\n  </tbody>\n</table>",
   "full": "<table>\n  <tbody>\n    <tr>\n      <td>help</td>\n      <td><a id=\"lsdoclink\" href=\"#\"></a> ; <a id=\"cheatsheetlink\" href=\"#\"></a></td>\n    </tr>\n    <tr>\n      <td>writing</td>\n      <td><a id=\"writinglink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>docs</td>\n      <td><a id=\"datadoclink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>related</td>\n      <td><a id=\"relatedlink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>data version</td>\n      <td><a id=\"datalink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>app version</td>\n      <td><span id=\"appversion\"></span></td>\n    </tr>\n  </tbody>\n</table> <p><a id=\"issuelink\" href=\"#\" class=\"medium active\"></a>\n  please copy the version above this line\n</p>"
  }
 },
 "defs": {
  "lsVersion": "v068@2021-05-11T18:16:50",
  "dataset": "bhsa",
  "client": "structure",
  "org": "annotation",
  "repo": "app-bhsa",
  "urls": {
   "cheatsheet": [
    "regexp cheatsheet",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet",
    "cheatsheet of regular expressions"
   ],
   "license": [
    "MIT",
    "https://mit-license.org",
    "website of MIT license"
   ],
   "maker": [
    null,
    "https://dans.knaw.nl/en/front-page?set_language=en",
    "Website of DANS = Data Archiving and Networked Services"
   ],
   "corpus": [
    null,
    "https://shebanq.ancient-data.org",
    "SHEBANQ website"
   ],
   "corpus2": [
    "Biblia Hebraica Stuttgartensia Amstelodamensis",
    "https://shebanq.ancient-data.org",
    "SHEBANQ website"
   ],
   "author": [
    "Dirk Roorda",
    "https://pure.knaw.nl/portal/en/persons/dirk-roorda",
    "profile of the author"
   ],
   "author1": [
    "Wido van Peursen",
    "https://research.vu.nl/en/persons/wido-van-peursen",
    "lead researcher"
   ],
   "author2": [
    "Dirk Roorda",
    "https://pure.knaw.nl/portal/en/persons/dirk-roorda",
    "data modeler"
   ],
   "tf": [
    null,
    "https://annotation.github.io/text-fabric/tf/",
    "Text-Fabric documentation website"
   ],
   "lsdoc": [
    "user manual (full)",
    "https://annotation.github.io/text-fabric/tf/about/clientmanual.html",
    "user manual for the full search interface"
   ],
   "lsdocsimple": [
    "user manual (simple)",
    "https://annotation.github.io/text-fabric/tf/about/manual.html",
    "user manual for the simplified search interface"
   ],
   "datadoc": [
    "data (feature) documentation",
    "https://etcbc.github.io/bhsa/features/0_home/",
    "explanation of the features in the dataset"
   ],
   "data": [
    "based on text-fabric data version 2017",
    "https://github.com/etcbc/bhsa/tree/master/tf/2017",
    "online repository of the underlying text-fabric data"
   ],
   "generator": [
    "text-fabric/client",
    "https://annotation.github.io/text-fabric/tf/client/make/build.html",
    "the generator of this search interface"
   ],
   "source": [
    "app-bhsa",
    "https://github.com/annotation/app-bhsa/tree/master/layeredsearch",
    "source code of the definition of this search interface"
   ],
   "issue": [
    "Report an issue",
    "https://github.com/annotation/app-bhsa/issues",
    "report issues"
   ],
   "package": [
    "download",
    "structure.zip",
    "zip file for offline use"
   ],
   "writing": [
    "hebrew",
    "https://annotation.github.io/text-fabric/tf/writing/hebrew.html",
    "characters and transliteration for hebrew"
   ],
   "related": [
    "text-fabric bhsa",
    "https://nbviewer.jupyter.org/github/annotation/tutorials/tree/master/bhsa/start.ipynb",
    "using Text-Fabric on the same corpus"
   ]
  },
  "description": "<p>Syntactic structure search interface for <a id=\"corpus2link\" href=\"#\"></a>.</p> <p>This search interface is by:</p> <ul>\n    <li><a id=\"author2link\" href=\"#\"></a> (data modeler)\n    <li><a id=\"author1link\" href=\"#\"></a> (lead researcher)\n</ul>"
 },
 "ntypes": [
  "word",
  "phrase",
  "clause",
  "sentence",
  "verse",
  "chapter",
  "book"
 ],
 "typesLower": {
  "word": [
   "word"
  ],
  "phrase": [
   "word",
   "phrase"
  ],
  "clause": [
   "word",
   "phrase",
   "clause"
  ],
  "sentence": [
   "word",
   "phrase",
   "clause",
   "sentence"
  ],
  "verse": [
   "word",
   "phrase",
   "clause",
   "sentence",
   "verse"
  ],
  "chapter": [
   "word",
   "phrase",
   "clause",
   "sentence",
   "verse",
   "chapter"
  ],
  "book": [
   "word",
   "phrase",
   "clause",
   "sentence",
   "verse",
   "chapter",
   "book"
  ]
 },
 "defaultSettings": {
  "autoexec": true,
  "nodeseq": true,
  "exporthl": true,
  "exportsr": true,
  "multihl": true,
  "simple": false
 },
 "defaultFlags": {
  "i": false,
  "m": true,
  "s": false
 },
 "keyboard": {
  "┣": "start of sentence",
  "┫": "end of sentence",
  "├": "start of sentence atom",
  "┤": "end of sentence atom",
  "┏": "start of clause",
  "┓": "end of clause",
  "┌": "start of clause atom",
  "┐": "end of clause atom",
  "◀": "start of phrase",
  "▶": "end of phrase",
  "◁": "start of phrase atom",
  "▷": "end of phrase atom"
 },
 "focusType": "sentence",
 "ntypesinit": {
  "book": 426585,
  "chapter": 426624,
  "lex": 1437403,
  "verse": 1414190,
  "half_verse": 606323,
  "sentence": 1172209,
  "sentence_atom": 1235920,
  "clause": 427553,
  "clause_atom": 515654,
  "phrase": 651503,
  "phrase_atom": 904690,
  "subphrase": 1300406,
  "word": 1
 },
 "ntypessize": {
  "book": 39,
  "chapter": 929,
  "lex": 9233,
  "verse": 23213,
  "half_verse": 45180,
  "sentence": 63711,
  "sentence_atom": 64486,
  "clause": 88101,
  "clause_atom": 90669,
  "phrase": 253187,
  "phrase_atom": 267519,
  "subphrase": 113784,
  "word": 426584
 },
 "dtypeOf": {
  "phrase": "word",
  "clause": "phrase",
  "sentence": "clause",
  "verse": "sentence",
  "chapter": "verse",
  "book": "chapter"
 },
 "utypeOf": {
  "word": "phrase",
  "phrase": "clause",
  "clause": "sentence",
  "sentence": "verse",
  "verse": "chapter",
  "chapter": "book"
 },
 "visible": {
  "word": {
   "lex": true,
   "pdp": true,
   "png": true,
   "vs": true,
   "vt": true
  },
  "phrase": {
   "ptype": false,
   "function": true
  },
  "clause": {
   "ttype": false,
   "ctype": false,
   "rela": true
  },
  "verse": {
   "number": true
  },
  "chapter": {
   "number": true
  },
  "book": {
   "book": true,
   "ref": false
  }
 },
 "levels": {
  "word": "words (some words do not have a space between them)",
  "phrase": "Phrases may have gaps.",
  "clause": "Clauses may have gaps.",
  "sentence": "Sentences may have gaps.",
  "verse": "Verses may split sentences.",
  "chapter": "Chapters.",
  "book": "Books."
 },
 "layers": {
  "word": {
   "lex": {
    "valueMap": null,
    "tip": false,
    "pos": "lex",
    "pattern": "",
    "description": "etcbc transcription of the lexemes"
   },
   "pdp": {
    "valueMap": [
     [
      "adjv",
      5391
     ],
     [
      "advb",
      6646
     ],
     [
      "art",
      29081
     ],
     [
      "conj",
      64555
     ],
     [
      "inrg",
      1357
     ],
     [
      "intj",
      1886
     ],
     [
      "nega",
      6789
     ],
     [
      "nmpr",
      33112
     ],
     [
      "prde",
      3135
     ],
     [
      "prep",
      74771
     ],
     [
      "prin",
      949
     ],
     [
      "prps",
      4508
     ],
     [
      "subs",
      125378
     ],
     [
      "verb",
      69026
     ]
    ],
    "tip": false,
    "pos": "pdp",
    "pattern": "",
    "description": "phrase-dependent part of speech"
   },
   "png": {
    "valueMap": [
     [
      "1p",
      1155
     ],
     [
      "1s",
      7183
     ],
     [
      "2pf",
      54
     ],
     [
      "2pm",
      3934
     ],
     [
      "2sf",
      835
     ],
     [
      "2sm",
      7458
     ],
     [
      "3p",
      4209
     ],
     [
      "3pf",
      378
     ],
     [
      "3pm",
      6721
     ],
     [
      "3sf",
      4298
     ],
     [
      "3sm",
      25294
     ],
     [
      "a",
      6138
     ],
     [
      "c",
      1363
     ],
     [
      "da",
      545
     ],
     [
      "dc",
      261
     ],
     [
      "dfa",
      1301
     ],
     [
      "dfc",
      526
     ],
     [
      "dfe",
      6
     ],
     [
      "dma",
      197
     ],
     [
      "dmc",
      22
     ],
     [
      "p",
      776
     ],
     [
      "pfa",
      5325
     ],
     [
      "pfc",
      1303
     ],
     [
      "pfe",
      23
     ],
     [
      "pma",
      22572
     ],
     [
      "pmc",
      8318
     ],
     [
      "pme",
      189
     ],
     [
      "s",
      10
     ],
     [
      "sa",
      19708
     ],
     [
      "sc",
      3138
     ],
     [
      "se",
      15
     ],
     [
      "sf",
      631
     ],
     [
      "sfa",
      17625
     ],
     [
      "sfc",
      4273
     ],
     [
      "sfe",
      141
     ],
     [
      "sm",
      1243
     ],
     [
      "sma",
      67646
     ],
     [
      "smc",
      20104
     ],
     [
      "sme",
      491
     ]
    ],
    "tip": false,
    "pos": "pdp",
    "pattern": "",
    "description": "person(123) number(sdp)  gender(mf) state(ace)"
   },
   "vs": {
    "valueMap": [
     [
      "NA",
      352874
     ],
     [
      "afel",
      4
     ],
     [
      "etpa",
      8
     ],
     [
      "etpe",
      3
     ],
     [
      "haf",
      163
     ],
     [
      "hif",
      9407
     ],
     [
      "hit",
      960
     ],
     [
      "hof",
      427
     ],
     [
      "hotp",
      8
     ],
     [
      "hsht",
      172
     ],
     [
      "htpa",
      30
     ],
     [
      "htpe",
      53
     ],
     [
      "htpo",
      3
     ],
     [
      "nif",
      4145
     ],
     [
      "nit",
      3
     ],
     [
      "pael",
      88
     ],
     [
      "pasq",
      6
     ],
     [
      "peal",
      654
     ],
     [
      "peil",
      40
     ],
     [
      "piel",
      6811
     ],
     [
      "poal",
      3
     ],
     [
      "poel",
      5
     ],
     [
      "pual",
      492
     ],
     [
      "qal",
      50205
     ],
     [
      "shaf",
      15
     ],
     [
      "tif",
      5
     ]
    ],
    "tip": false,
    "pos": "pdp",
    "pattern": "",
    "description": "verbal stem"
   },
   "vt": {
    "valueMap": [
     [
      "NA",
      352874
     ],
     [
      "impf",
      16099
     ],
     [
      "impv",
      4307
     ],
     [
      "infa",
      894
     ],
     [
      "infc",
      6607
     ],
     [
      "perf",
      21128
     ],
     [
      "ptca",
      8403
     ],
     [
      "ptcp",
      1298
     ],
     [
      "wayq",
      14974
     ]
    ],
    "tip": false,
    "pos": "pdp",
    "pattern": "",
    "description": "verbal tense"
   }
  },
  "phrase": {
   "ptype": {
    "valueMap": [
     [
      "AdjP",
      3547
     ],
     [
      "AdvP",
      11546
     ],
     [
      "AjCl",
      2870
     ],
     [
      "CP",
      106259
     ],
     [
      "CPen",
      2580
     ],
     [
      "DPrP",
      1580
     ],
     [
      "Defc",
      2568
     ],
     [
      "Ellp",
      5556
     ],
     [
      "IPrP",
      1593
     ],
     [
      "InfA",
      602
     ],
     [
      "InfC",
      13038
     ],
     [
      "InjP",
      3744
     ],
     [
      "InrP",
      2582
     ],
     [
      "MSyn",
      1934
     ],
     [
      "NP",
      88317
     ],
     [
      "NegP",
      13486
     ],
     [
      "NmCl",
      22752
     ],
     [
      "PP",
      120040
     ],
     [
      "PPrP",
      8841
     ],
     [
      "PrNP",
      21121
     ],
     [
      "Ptcp",
      10864
     ],
     [
      "Reop",
      20
     ],
     [
      "VP",
      138050
     ],
     [
      "Voct",
      3262
     ],
     [
      "WIm0",
      1773
     ],
     [
      "WImX",
      6
     ],
     [
      "WQt0",
      10206
     ],
     [
      "WQtX",
      2630
     ],
     [
      "WXIm",
      82
     ],
     [
      "WXQt",
      2719
     ],
     [
      "WXYq",
      2615
     ],
     [
      "WYq0",
      2380
     ],
     [
      "WYqX",
      486
     ],
     [
      "Way0",
      18110
     ],
     [
      "WayX",
      11760
     ],
     [
      "WxI0",
      153
     ],
     [
      "WxQ0",
      3011
     ],
     [
      "WxQX",
      919
     ],
     [
      "WxY0",
      4834
     ],
     [
      "WxYX",
      826
     ],
     [
      "XImp",
      23
     ],
     [
      "XPos",
      52
     ],
     [
      "XQtl",
      2727
     ],
     [
      "XYqt",
      2836
     ],
     [
      "ZIm0",
      6000
     ],
     [
      "ZImX",
      67
     ],
     [
      "ZQt0",
      2993
     ],
     [
      "ZQtX",
      1587
     ],
     [
      "ZYq0",
      3099
     ],
     [
      "ZYqX",
      1182
     ],
     [
      "xIm0",
      504
     ],
     [
      "xImX",
      6
     ],
     [
      "xQt0",
      9702
     ],
     [
      "xQtX",
      5534
     ],
     [
      "xYq0",
      10828
     ],
     [
      "xYqX",
      3074
     ]
    ],
    "tip": false,
    "pos": "ptype",
    "pattern": "",
    "description": "phrase type"
   },
   "function": {
    "valueMap": [
     [
      "Adju",
      9532
     ],
     [
      "Cmpl",
      30026
     ],
     [
      "Conj",
      46144
     ],
     [
      "EPPr",
      21
     ],
     [
      "ExsS",
      14
     ],
     [
      "Exst",
      143
     ],
     [
      "Frnt",
      1138
     ],
     [
      "IntS",
      251
     ],
     [
      "Intj",
      1621
     ],
     [
      "Loca",
      2624
     ],
     [
      "ModS",
      35
     ],
     [
      "Modi",
      3744
     ],
     [
      "NCoS",
      101
     ],
     [
      "NCop",
      595
     ],
     [
      "Nega",
      6047
     ],
     [
      "Objc",
      22653
     ],
     [
      "PrAd",
      245
     ],
     [
      "PrcS",
      8
     ],
     [
      "PreC",
      19383
     ],
     [
      "PreO",
      5402
     ],
     [
      "PreS",
      887
     ],
     [
      "Pred",
      57070
     ],
     [
      "PtcO",
      163
     ],
     [
      "Ques",
      1203
     ],
     [
      "Rela",
      6330
     ],
     [
      "Subj",
      31946
     ],
     [
      "Supp",
      178
     ],
     [
      "Time",
      4077
     ],
     [
      "Voct",
      1606
     ]
    ],
    "tip": false,
    "pos": "ptype",
    "pattern": "",
    "description": "phrase function"
   }
  },
  "clause": {
   "ttype": {
    "valueMap": [
     [
      "?",
      3510
     ],
     [
      "??",
      778
     ],
     [
      "???",
      125
     ],
     [
      "????",
      15
     ],
     [
      "?????",
      6
     ],
     [
      "??????",
      3
     ],
     [
      "???????",
      37
     ],
     [
      "???N",
      29
     ],
     [
      "???Q",
      10
     ],
     [
      "???QQ",
      2
     ],
     [
      "???QQQ",
      12
     ],
     [
      "??N",
      483
     ],
     [
      "??ND",
      30
     ],
     [
      "??NDN",
      11
     ],
     [
      "??NDND",
      9
     ],
     [
      "??NDNDN",
      4
     ],
     [
      "??NQ",
      132
     ],
     [
      "??NQQ",
      9
     ],
     [
      "??Q",
      299
     ],
     [
      "??QN",
      1
     ],
     [
      "??QNQ",
      2
     ],
     [
      "??QQ",
      21
     ],
     [
      "?N",
      3713
     ],
     [
      "?ND",
      97
     ],
     [
      "?NDN",
      30
     ],
     [
      "?NDNQ",
      3
     ],
     [
      "?NDQ",
      1
     ],
     [
      "?NQ",
      2401
     ],
     [
      "?NQN",
      298
     ],
     [
      "?NQND",
      22
     ],
     [
      "?NQNDN",
      18
     ],
     [
      "?NQNDNQ",
      6
     ],
     [
      "?NQNQ",
      85
     ],
     [
      "?NQNQN",
      13
     ],
     [
      "?NQNQQ",
      12
     ],
     [
      "?NQQ",
      454
     ],
     [
      "?NQQN",
      49
     ],
     [
      "?NQQNQ",
      2
     ],
     [
      "?NQQQ",
      148
     ],
     [
      "?NQQQN",
      14
     ],
     [
      "?NQQQNQ",
      1
     ],
     [
      "?NQQQQ",
      7
     ],
     [
      "?Q",
      3019
     ],
     [
      "?QN",
      165
     ],
     [
      "?QND",
      26
     ],
     [
      "?QNQ",
      89
     ],
     [
      "?QNQQ",
      27
     ],
     [
      "?QNQQQ",
      11
     ],
     [
      "?QQ",
      951
     ],
     [
      "?QQN",
      34
     ],
     [
      "?QQNQ",
      5
     ],
     [
      "?QQQ",
      321
     ],
     [
      "?QQQN",
      26
     ],
     [
      "?QQQND",
      1
     ],
     [
      "?QQQNQ",
      4
     ],
     [
      "?QQQQ",
      103
     ],
     [
      "?QQQQN",
      2
     ],
     [
      "?QQQQQ",
      34
     ],
     [
      "?QQQQQQ",
      1
     ],
     [
      "D",
      1222
     ],
     [
      "DN",
      106
     ],
     [
      "DND",
      3
     ],
     [
      "DNQ",
      273
     ],
     [
      "DNQN",
      19
     ],
     [
      "DNQNQ",
      8
     ],
     [
      "DNQQ",
      19
     ],
     [
      "DNQQN",
      2
     ],
     [
      "DQ",
      444
     ],
     [
      "DQN",
      8
     ],
     [
      "DQQ",
      43
     ],
     [
      "N",
      19866
     ],
     [
      "ND",
      532
     ],
     [
      "NDN",
      132
     ],
     [
      "NDND",
      6
     ],
     [
      "NDNQ",
      41
     ],
     [
      "NDNQN",
      3
     ],
     [
      "NDNQQ",
      5
     ],
     [
      "NDNQQN",
      5
     ],
     [
      "NDQ",
      57
     ],
     [
      "NDQN",
      4
     ],
     [
      "NDQQ",
      1
     ],
     [
      "NQ",
      16509
     ],
     [
      "NQN",
      1062
     ],
     [
      "NQND",
      168
     ],
     [
      "NQNDN",
      16
     ],
     [
      "NQNDND",
      1
     ],
     [
      "NQNDQ",
      10
     ],
     [
      "NQNQ",
      495
     ],
     [
      "NQNQN",
      9
     ],
     [
      "NQNQNQ",
      1
     ],
     [
      "NQNQQ",
      24
     ],
     [
      "NQNQQQ",
      8
     ],
     [
      "NQQ",
      4435
     ],
     [
      "NQQN",
      250
     ],
     [
      "NQQND",
      21
     ],
     [
      "NQQNQ",
      23
     ],
     [
      "NQQNQQ",
      5
     ],
     [
      "NQQQ",
      1723
     ],
     [
      "NQQQN",
      283
     ],
     [
      "NQQQND",
      39
     ],
     [
      "NQQQNDN",
      47
     ],
     [
      "NQQQNQ",
      48
     ],
     [
      "NQQQNQN",
      3
     ],
     [
      "NQQQQ",
      259
     ],
     [
      "NQQQQN",
      18
     ],
     [
      "NQQQQQ",
      112
     ],
     [
      "NQQQQQN",
      10
     ],
     [
      "NQQQQQQ",
      1
     ],
     [
      "Q",
      16367
     ],
     [
      "QN",
      1433
     ],
     [
      "QND",
      267
     ],
     [
      "QNDN",
      18
     ],
     [
      "QNDND",
      1
     ],
     [
      "QNDQ",
      55
     ],
     [
      "QNDQQ",
      3
     ],
     [
      "QNQ",
      714
     ],
     [
      "QNQN",
      38
     ],
     [
      "QNQND",
      1
     ],
     [
      "QNQQ",
      109
     ],
     [
      "QNQQN",
      3
     ],
     [
      "QNQQQ",
      64
     ],
     [
      "QNQQQQ",
      12
     ],
     [
      "QNQQQQQ",
      11
     ],
     [
      "QQ",
      2315
     ],
     [
      "QQN",
      136
     ],
     [
      "QQND",
      17
     ],
     [
      "QQNQ",
      25
     ],
     [
      "QQQ",
      257
     ],
     [
      "QQQN",
      4
     ],
     [
      "QQQNQ",
      1
     ],
     [
      "QQQNQQ",
      1
     ],
     [
      "QQQQ",
      90
     ],
     [
      "QQQQN",
      4
     ],
     [
      "QQQQQ",
      22
     ],
     [
      "QQQQQN",
      1
     ],
     [
      "QQQQQQ",
      32
     ]
    ],
    "tip": false,
    "pos": "ttype",
    "pattern": "",
    "description": "text type"
   },
   "ctype": {
    "valueMap": [
     [
      "AdjP",
      3547
     ],
     [
      "AdvP",
      11546
     ],
     [
      "AjCl",
      2870
     ],
     [
      "CP",
      106259
     ],
     [
      "CPen",
      2580
     ],
     [
      "DPrP",
      1580
     ],
     [
      "Defc",
      2568
     ],
     [
      "Ellp",
      5556
     ],
     [
      "IPrP",
      1593
     ],
     [
      "InfA",
      602
     ],
     [
      "InfC",
      13038
     ],
     [
      "InjP",
      3744
     ],
     [
      "InrP",
      2582
     ],
     [
      "MSyn",
      1934
     ],
     [
      "NP",
      88317
     ],
     [
      "NegP",
      13486
     ],
     [
      "NmCl",
      22752
     ],
     [
      "PP",
      120040
     ],
     [
      "PPrP",
      8841
     ],
     [
      "PrNP",
      21121
     ],
     [
      "Ptcp",
      10864
     ],
     [
      "Reop",
      20
     ],
     [
      "VP",
      138050
     ],
     [
      "Voct",
      3262
     ],
     [
      "WIm0",
      1773
     ],
     [
      "WImX",
      6
     ],
     [
      "WQt0",
      10206
     ],
     [
      "WQtX",
      2630
     ],
     [
      "WXIm",
      82
     ],
     [
      "WXQt",
      2719
     ],
     [
      "WXYq",
      2615
     ],
     [
      "WYq0",
      2380
     ],
     [
      "WYqX",
      486
     ],
     [
      "Way0",
      18110
     ],
     [
      "WayX",
      11760
     ],
     [
      "WxI0",
      153
     ],
     [
      "WxQ0",
      3011
     ],
     [
      "WxQX",
      919
     ],
     [
      "WxY0",
      4834
     ],
     [
      "WxYX",
      826
     ],
     [
      "XImp",
      23
     ],
     [
      "XPos",
      52
     ],
     [
      "XQtl",
      2727
     ],
     [
      "XYqt",
      2836
     ],
     [
      "ZIm0",
      6000
     ],
     [
      "ZImX",
      67
     ],
     [
      "ZQt0",
      2993
     ],
     [
      "ZQtX",
      1587
     ],
     [
      "ZYq0",
      3099
     ],
     [
      "ZYqX",
      1182
     ],
     [
      "xIm0",
      504
     ],
     [
      "xImX",
      6
     ],
     [
      "xQt0",
      9702
     ],
     [
      "xQtX",
      5534
     ],
     [
      "xYq0",
      10828
     ],
     [
      "xYqX",
      3074
     ]
    ],
    "tip": false,
    "pos": "ctype",
    "pattern": "",
    "description": "clause type"
   },
   "rela": {
    "valueMap": [
     [
      "Adju",
      6414
     ],
     [
      "Appo",
      5887
     ],
     [
      "Attr",
      6352
     ],
     [
      "Cmpl",
      299
     ],
     [
      "Coor",
      3639
     ],
     [
      "Link",
      1311
     ],
     [
      "NA",
      630012
     ],
     [
      "Objc",
      1324
     ],
     [
      "Para",
      1553
     ],
     [
      "PrAd",
      257
     ],
     [
      "PreC",
      169
     ],
     [
      "ReVo",
      312
     ],
     [
      "Resu",
      1618
     ],
     [
      "RgRc",
      394
     ],
     [
      "Sfxs",
      74
     ],
     [
      "Spec",
      5579
     ],
     [
      "Subj",
      505
     ],
     [
      "adj",
      4180
     ],
     [
      "atr",
      3113
     ],
     [
      "dem",
      1847
     ],
     [
      "mod",
      937
     ],
     [
      "par",
      11932
     ],
     [
      "rec",
      34883
     ]
    ],
    "tip": false,
    "pos": "ctype",
    "pattern": "",
    "description": "clause relation"
   }
  },
  "verse": {
   "number": {
    "valueMap": null,
    "tip": false,
    "pos": "number",
    "pattern": "",
    "description": "verse number"
   }
  },
  "chapter": {
   "number": {
    "valueMap": null,
    "tip": false,
    "pos": "number",
    "pattern": "",
    "description": "chapter number"
   }
  },
  "book": {
   "book": {
    "valueMap": null,
    "tip": false,
    "pos": "book",
    "pattern": "",
    "description": "name of a book"
   },
   "ref": {
    "valueMap": null,
    "tip": false,
    "pos": "ref",
    "pattern": "",
    "description": "latin name of a book"
   }
  }
 }
}